backend:
  name: github
  repo: tshimizu-lab/tshimizu-lab.github.io
  branch: master
  client_id: Ov23libTO6ad0YQFo6QH
  base_url: https://netlify-cms-github-oauth.netlify.app
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"  
    label: "投稿"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime" }
      - { label: "本文", name: "body", widget: "markdown" }
