backend:
  name: github
  repo: tshimizu-lab/tshimizu-lab.github.io
  branch: main
  client_id: Ov23libTO6ad0YQFo6QH
  base_url: https://decapcms-oauth.netlify.app
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{% raw %}{{year}}-{{month}}-{{day}}-{{slug}}{% endraw %}"
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { label: "body", name: "body", widget: "markdown" }